function Hd = notch_50_application
%5_NOTCH_APPLICATION Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 19-Sep-2023 15:24:00

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 500;  % Sampling Frequency

Fnotch = 50;  % Notch Frequency
BW     = 3;   % Bandwidth
Apass  = 1;   % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);

freqz(b,a,1024,500);
Hd     = dfilt.df2(b, a);

% [EOF]
